// Code generated by sqlc. DO NOT EDIT.
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin (name, email, password) VALUES ($1, $2, $3) RETURNING id, name, email
`

type CreateAdminParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateAdminRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (CreateAdminRow, error) {
	row := q.queryRow(ctx, q.createAdminStmt, createAdmin, arg.Name, arg.Email, arg.Password)
	var i CreateAdminRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const login = `-- name: Login :one
SELECT id, name, email, password FROM admin WHERE email = ($1)
`

type LoginRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
}

func (q *Queries) Login(ctx context.Context, email string) (LoginRow, error) {
	row := q.queryRow(ctx, q.loginStmt, login, email)
	var i LoginRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}
