// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, college_name, address, mobile_no, image_path, image_uid) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, name, college_name, address, mobile_no, image_uid
`

type CreateUserParams struct {
	Name        sql.NullString `json:"name"`
	CollegeName sql.NullString `json:"college_name"`
	Address     sql.NullString `json:"address"`
	MobileNo    sql.NullInt32  `json:"mobile_no"`
	ImagePath   string         `json:"image_path"`
	ImageUid    string         `json:"image_uid"`
}

type CreateUserRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	CollegeName sql.NullString `json:"college_name"`
	Address     sql.NullString `json:"address"`
	MobileNo    sql.NullInt32  `json:"mobile_no"`
	ImageUid    string         `json:"image_uid"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Name,
		arg.CollegeName,
		arg.Address,
		arg.MobileNo,
		arg.ImagePath,
		arg.ImageUid,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CollegeName,
		&i.Address,
		&i.MobileNo,
		&i.ImageUid,
	)
	return i, err
}

const deleteUsersById = `-- name: DeleteUsersById :exec
DELETE FROM users WHERE image_uid = $1
`

func (q *Queries) DeleteUsersById(ctx context.Context, imageUid string) error {
	_, err := q.exec(ctx, q.deleteUsersByIdStmt, deleteUsersById, imageUid)
	return err
}

const readAllUsers = `-- name: ReadAllUsers :many
SELECT id, name, college_name, address, mobile_no, image_path, image_uid FROM users WHERE is_deleted = false
`

type ReadAllUsersRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	CollegeName sql.NullString `json:"college_name"`
	Address     sql.NullString `json:"address"`
	MobileNo    sql.NullInt32  `json:"mobile_no"`
	ImagePath   string         `json:"image_path"`
	ImageUid    string         `json:"image_uid"`
}

func (q *Queries) ReadAllUsers(ctx context.Context) ([]ReadAllUsersRow, error) {
	rows, err := q.query(ctx, q.readAllUsersStmt, readAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadAllUsersRow
	for rows.Next() {
		var i ReadAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CollegeName,
			&i.Address,
			&i.MobileNo,
			&i.ImagePath,
			&i.ImageUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readUserByID = `-- name: ReadUserByID :one
SELECT id, name, college_name, address, mobile_no, image_path, image_uid FROM users WHERE is_deleted = false AND image_uid = ($1)
`

type ReadUserByIDRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	CollegeName sql.NullString `json:"college_name"`
	Address     sql.NullString `json:"address"`
	MobileNo    sql.NullInt32  `json:"mobile_no"`
	ImagePath   string         `json:"image_path"`
	ImageUid    string         `json:"image_uid"`
}

func (q *Queries) ReadUserByID(ctx context.Context, imageUid string) (ReadUserByIDRow, error) {
	row := q.queryRow(ctx, q.readUserByIDStmt, readUserByID, imageUid)
	var i ReadUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CollegeName,
		&i.Address,
		&i.MobileNo,
		&i.ImagePath,
		&i.ImageUid,
	)
	return i, err
}

const readUsersByFace = `-- name: ReadUsersByFace :many
SELECT id, name, college_name, address, mobile_no, image_path, image_uid FROM users WHERE is_deleted = false AND image_uid = ANY($1::text[])
`

type ReadUsersByFaceRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	CollegeName sql.NullString `json:"college_name"`
	Address     sql.NullString `json:"address"`
	MobileNo    sql.NullInt32  `json:"mobile_no"`
	ImagePath   string         `json:"image_path"`
	ImageUid    string         `json:"image_uid"`
}

func (q *Queries) ReadUsersByFace(ctx context.Context, dollar_1 []string) ([]ReadUsersByFaceRow, error) {
	rows, err := q.query(ctx, q.readUsersByFaceStmt, readUsersByFace, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadUsersByFaceRow
	for rows.Next() {
		var i ReadUsersByFaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CollegeName,
			&i.Address,
			&i.MobileNo,
			&i.ImagePath,
			&i.ImageUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = ($2), college_name = ($3), address = ($4), mobile_no = ($5), image_path = ($6), image_uid = ($7) WHERE image_uid = ($1) RETURNING id, index, name, college_name, address, mobile_no, image_path, image_uid, is_deleted, created_at, updated_at
`

type UpdateUserParams struct {
	ImageUid    string         `json:"image_uid"`
	Name        sql.NullString `json:"name"`
	CollegeName sql.NullString `json:"college_name"`
	Address     sql.NullString `json:"address"`
	MobileNo    sql.NullInt32  `json:"mobile_no"`
	ImagePath   string         `json:"image_path"`
	ImageUid_2  string         `json:"image_uid_2"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.ImageUid,
		arg.Name,
		arg.CollegeName,
		arg.Address,
		arg.MobileNo,
		arg.ImagePath,
		arg.ImageUid_2,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Index,
		&i.Name,
		&i.CollegeName,
		&i.Address,
		&i.MobileNo,
		&i.ImagePath,
		&i.ImageUid,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
