// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Admin struct {
	ID        uuid.UUID     `json:"id"`
	Index     sql.NullInt32 `json:"index"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Password  string        `json:"password"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Post struct {
	ID        uuid.UUID     `json:"id"`
	Index     sql.NullInt32 `json:"index"`
	PostName  string        `json:"post_name"`
	PostData  string        `json:"post_data"`
	Tags      []string      `json:"tags"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Index       sql.NullInt32  `json:"index"`
	Name        sql.NullString `json:"name"`
	CollegeName sql.NullString `json:"college_name"`
	Address     sql.NullString `json:"address"`
	MobileNo    sql.NullInt32  `json:"mobile_no"`
	ImagePath   string         `json:"image_path"`
	ImageUid    string         `json:"image_uid"`
	IsDeleted   sql.NullBool   `json:"is_deleted"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
