version: '3.2'
services:
  face_recognition:
    restart: always
    image: postgres:10.5
    environment:
      - POSTGRES_DB=face_recognition
      - POSTGRES_USER=face_recognition
      - POSTGRES_PASSWORD=face_recognition
    ports:
      - "5431:5432"
    volumes:
      - fc_db_data:/var/lib/postgresql/data
volumes:
  fc_db_data:
